name: Context Demo

on:
  workflow_dispatch:

jobs:
  show-context:
    runs-on: ubuntu-latest

    steps:
      - name: Show GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Show Runner context
        run: echo '${{ toJSON(runner) }}'

      - name: Show Environment variables
        run: echo '${{ toJSON(env) }}'
