name: Frontend CI (React)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5   # ✅ upgrade

    - name: Setup Node
      uses: actions/setup-node@v5   # ✅ upgrade
      with:
        node-version: 20
        cache: npm

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm test || echo "Skipping tests"

    - name: Build
      run: npm run build
